services:

  frontend:
    build: ./frontend
    container_name: react-frontend

    ports:
      - "3001:3000"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    restart: always

    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: fastapi-backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    restart: always
